name = "worker-typescript"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-12-01"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
